version: '3.2'

services:
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    networks:
      development:
        ipv4_address: 172.20.0.100
    ports:
    - 80:80
    - 443:443
    - 32700:32700

  apache74:
    container_name: apache74
    build:
      context: .
      dockerfile: ./php74/Dockerfile
    volumes:
      - 'D:/var/www:/var/www/html'
    networks:
      development:
        ipv4_address: 172.20.0.74
    expose:
    - 80
    - 443
    extra_hosts:
      - "development.local:127.0.0.1"

  apache73:
    container_name: apache73
    build:
      context: .
      dockerfile: ./php73/Dockerfile
    volumes:
      - 'D:/var/www:/var/www/html'
    networks:
      development:
        ipv4_address: 172.20.0.73
    expose:
    - 80
    - 443
    extra_hosts:
      - "development.local:127.0.0.1"

  apache72:
    container_name: apache72
    build:
      context: .
      dockerfile: ./php72/Dockerfile
    volumes:
      - 'D:/var/www:/var/www/html'
    networks:
      development:
        ipv4_address: 172.20.0.72
    expose:
    - 80
    - 443
    extra_hosts:
      - "development.local:127.0.0.1"

  apache56:
    container_name: apache56
    build:
      context: .
      dockerfile: ./php56/Dockerfile
    volumes:
      - 'D:/var/www:/var/www/html'
    networks:
      development:
        ipv4_address: 172.20.0.56
    expose:
    - 80
    - 443
    extra_hosts:
      - "development.local:127.0.0.1"

  pentesting:
    container_name: pentesting
    build:
      context: .
      dockerfile: ./pentesting/Dockerfile
    volumes:
      - 'D:/var/www:/var/www/html'
    networks:
      development:
        ipv4_address: 172.20.0.99
    extra_hosts:
      - "development.local:172.20.0.100"

  zap:
    container_name: zap
    build:
      context: .
      dockerfile: ./zap/Dockerfile
    volumes:
      - 'D:/var/www:/var/www/html'
    networks:
      development:
        ipv4_address: 172.20.0.98
    ports:
    - 2375:2375
    extra_hosts:
      - "development.local:172.20.0.100"

networks:
  development:
    external: true
